// HomeScreen.styles.ts
import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

// ── Design tokens ──────────────────────────────────────────────────────────
export const C = {
    bg:          '#F8FAF5',
    surface:     '#FFFFFF',
    brand:       '#5A8A2E',
    brandDark:   '#3B6D11',
    brandLight:  '#EAF3DE',
    blue:        '#185FA5',
    blueLight:   '#E6F1FB',
    purple:      '#7E22CE',
    purpleLight: '#F3E8FF',
    amber:       '#D97706',
    amberLight:  '#FFF7ED',
    orange:      '#EA580C',
    orangeLight: '#FFF1EB',
    text:        '#111111',
    muted:       '#9CA3AF',
    mutedLight:  '#F3F4F6',
} as const;

export const SP = { xs: 8, sm: 12, md: 16, lg: 24, xl: 32 } as const;

export const shadow = {
    sm: Platform.select({
        ios:     { shadowColor: '#000',    shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4,  elevation: 2 },
        android: { elevation: 2 },
        default: {},
    }),
    md: Platform.select({
        ios:     { shadowColor: '#3B6D11', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.10, shadowRadius: 12, elevation: 5 },
        android: { elevation: 5 },
        default: {},
    }),
    lg: Platform.select({
        ios:     { shadowColor: '#7E22CE', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.15, shadowRadius: 18, elevation: 8 },
        android: { elevation: 8 },
        default: {},
    }),
    orange: Platform.select({
        ios:     { shadowColor: '#EA580C', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.20, shadowRadius: 12, elevation: 5 },
        android: { elevation: 5 },
        default: {},
    }),
} as const;

// ── Styles ─────────────────────────────────────────────────────────────────
export const s = StyleSheet.create({
    safe: { flex: 1, backgroundColor: C.bg },

    heroBanner:     { backgroundColor: C.brandDark, overflow: 'hidden', paddingHorizontal: SP.md, paddingTop: SP.md, paddingBottom: SP.lg + 4 },
    bannerCircle1:  { position: 'absolute', width: 160, height: 160, borderRadius: 80,  backgroundColor: '#4A8020', opacity: 0.45, right: -40, top: -50 },
    bannerCircle2:  { position: 'absolute', width: 100, height: 100, borderRadius: 50,  backgroundColor: '#6AAD30', opacity: 0.25, left: -20, bottom: -30 },
    bannerRow:      { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
    bannerLeft:     { flex: 1, paddingRight: SP.sm },
    bannerGreeting: { fontSize: 12, color: 'rgba(255,255,255,0.65)', fontWeight: '500', marginBottom: 4, letterSpacing: 0.3 },
    bannerName:     { fontSize: 22, fontWeight: '800', color: '#FFFFFF', marginBottom: 6 },
    levelBadge:     { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-start', backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
    levelText:      { fontSize: 11, fontWeight: '700', color: 'rgba(255,255,255,0.9)' },
    bannerRight:    { alignItems: 'center', gap: SP.xs },
    streakPill:     { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 20, paddingHorizontal: SP.xs, paddingVertical: 4, gap: 3 },
    streakFire:     { fontSize: 12 },
    streakCount:    { fontSize: 11, fontWeight: '800', color: '#FFFFFF' },

    scroll:        { flex: 1 },
    scrollContent: { paddingHorizontal: SP.md, paddingTop: SP.md },

    statsLoadingRow: { height: 72, alignItems: 'center', justifyContent: 'center', marginBottom: SP.md },
    statsRow:  { flexDirection: 'row', gap: SP.xs, marginBottom: SP.md },
    statChip:  { flex: 1, borderRadius: 16, padding: SP.sm, alignItems: 'center', gap: 3 },
    statValue: { fontSize: 16, fontWeight: '800' },
    statLabel: { fontSize: 10, fontWeight: '600', color: C.muted, letterSpacing: 0.3 },

    sectionLabel: { fontSize: 11, fontWeight: '600', color: C.muted, letterSpacing: 0.8, marginBottom: SP.sm },

    gridRow:     { flexDirection: 'row', gap: SP.sm, marginBottom: SP.sm },
    card:        { flex: 1, backgroundColor: C.surface, borderRadius: 24, padding: SP.md },
    iconBox:     { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: SP.sm },
    cardTitle:   { fontSize: 15, fontWeight: '800', color: C.text, marginBottom: 4 },
    cardDesc:    { fontSize: 11, color: C.muted, lineHeight: 16, marginBottom: SP.md, flex: 1 },
    cardBtn:     { height: 40, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, overflow: 'hidden' },
    cardBtnText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },

    dictationCard:      { backgroundColor: '#FFF7ED', borderRadius: 24, padding: SP.md, marginBottom: SP.sm, overflow: 'hidden', minHeight: 130, borderWidth: 1.5, borderColor: '#FFEDD5' },
    dictationBlob1:     { position: 'absolute', width: 110, height: 110, borderRadius: 55, backgroundColor: '#FED7AA', right: -20, top: -20, opacity: 0.6 },
    dictationBlob2:     { position: 'absolute', width: 70,  height: 70,  borderRadius: 35, backgroundColor: '#FDBA74', right: 35,  bottom: -20, opacity: 0.4 },
    dictationRow:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    dictationLeft:      { flex: 1 },
    dictationBadge:     { alignSelf: 'flex-start', backgroundColor: '#FFEDD5', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4, marginBottom: 8 },
    dictationBadgeText: { fontSize: 11, fontWeight: '700', color: C.orange, letterSpacing: 0.3 },
    dictationTitle:     { fontSize: 18, fontWeight: '800', color: C.orange, marginBottom: 4, lineHeight: 24 },
    dictationDesc:      { fontSize: 11, color: '#9A3412', opacity: 0.7, lineHeight: 16, marginBottom: SP.sm },
    dictationBtn:       { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-start', backgroundColor: '#FFEDD5', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8 },
    dictationBtnText:   { fontSize: 13, fontWeight: '700', color: C.orange },
    dictationIconWrap:  { width: 80, height: 80, alignItems: 'center', justifyContent: 'center' },
    dictationRing3:     { position: 'absolute', width: 78, height: 78, borderRadius: 39, backgroundColor: '#FED7AA', opacity: 0.3 },
    dictationRing2:     { position: 'absolute', width: 58, height: 58, borderRadius: 29, backgroundColor: '#FDBA74', opacity: 0.35 },
    dictationRing1:     { position: 'absolute', width: 44, height: 44, borderRadius: 22, backgroundColor: '#FB923C', opacity: 0.25 },
    dictationCore:      { width: 40, height: 40, borderRadius: 20, backgroundColor: '#FFEDD5', alignItems: 'center', justifyContent: 'center' },

    heroCard:        { backgroundColor: '#FAF5FF', borderRadius: 24, padding: SP.md, marginBottom: SP.lg, overflow: 'hidden', minHeight: 140 },
    heroBlobA:       { position: 'absolute', width: 120, height: 120, borderRadius: 60, backgroundColor: '#EDE9FE', right: -20, top: -20, opacity: 0.7 },
    heroBlobB:       { position: 'absolute', width: 80,  height: 80,  borderRadius: 40, backgroundColor: '#DDD6FE', right: 40,  bottom: -20, opacity: 0.5 },
    aiBadge:         { alignSelf: 'flex-start', backgroundColor: '#EDE9FE', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4, marginBottom: SP.sm },
    aiBadgeText:     { fontSize: 11, fontWeight: '700', color: C.purple, letterSpacing: 0.4 },
    heroCardRow:     { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    heroCardLeft:    { flex: 1 },
    heroCardTitle:   { fontSize: 20, fontWeight: '800', color: C.purple, marginBottom: 4 },
    heroCardDesc:    { fontSize: 12, color: '#7C3AED', opacity: 0.7, lineHeight: 17, marginBottom: SP.sm },
    heroCardBtn:     { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-start', backgroundColor: '#EDE9FE', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8 },
    heroCardBtnText: { fontSize: 13, fontWeight: '700', color: C.purple },
    micWrap:  { width: 90, height: 90, alignItems: 'center', justifyContent: 'center' },
    micRing3: { position: 'absolute', width: 88, height: 88, borderRadius: 44, backgroundColor: '#DDD6FE', opacity: 0.3 },
    micRing2: { position: 'absolute', width: 66, height: 66, borderRadius: 33, backgroundColor: '#C4B5FD', opacity: 0.35 },
    micRing1: { position: 'absolute', width: 50, height: 50, borderRadius: 25, backgroundColor: '#A78BFA', opacity: 0.25 },
    micCore:  { width: 44, height: 44, borderRadius: 22, backgroundColor: '#EDE9FE', alignItems: 'center', justifyContent: 'center' },

    lbContainer:  { backgroundColor: C.surface, borderRadius: 24, padding: SP.md, marginBottom: SP.lg },
    lbHeader:     { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: SP.sm },
    lbTitle:      { fontSize: 17, fontWeight: '800', color: C.text },
    lbSubtitle:   { fontSize: 11, color: C.muted, marginTop: 2 },
    lbTabBar:     { flexDirection: 'row', backgroundColor: C.mutedLight, borderRadius: 14, padding: 3, marginBottom: SP.sm },
    lbTab:        { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 8, borderRadius: 11 },
    lbTabActive:  { backgroundColor: C.surface },
    lbTabText:    { fontSize: 12, fontWeight: '600', color: C.muted },
    myRankBadge:  { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, backgroundColor: C.mutedLight, borderRadius: 20, paddingVertical: 6, paddingHorizontal: 12, alignSelf: 'center', marginBottom: SP.sm },
    myRankText:   { fontSize: 12, color: C.muted },
    myRankNum:    { fontSize: 12, fontWeight: '800', color: C.text },
    lbLoading:    { height: 120, alignItems: 'center', justifyContent: 'center' },
    lbEmpty:      { height: 120, alignItems: 'center', justifyContent: 'center', gap: 8 },
    lbEmptyText:  { fontSize: 13, color: C.muted },

    podiumRow:           { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', gap: SP.xs, marginBottom: SP.md, paddingTop: SP.lg },
    podiumItem:          { alignItems: 'center' },
    podiumCrown:         { fontSize: 20, marginBottom: 4 },
    podiumAvatarWrap:    { marginBottom: 4 },
    podiumRankBadge:     { position: 'absolute', top: -4, right: -4, width: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#FFFFFF' },
    podiumRankBadgeText: { fontSize: 9, fontWeight: '700' },
    podiumName:          { fontSize: 11, fontWeight: '600', color: C.text, textAlign: 'center', marginBottom: 2, maxWidth: 110 },
    podiumMeBadge:       { backgroundColor: '#D1FAE5', borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2, marginBottom: 4 },
    podiumMeText:        { fontSize: 9, fontWeight: '700', color: '#065F46' },
    podiumValue:         { flexDirection: 'row', alignItems: 'center', gap: 2, marginBottom: 6 },
    podiumValueText:     { fontSize: 12, fontWeight: '800' },
    podiumUnit:          { fontSize: 10, color: C.muted },
    podiumBlock:         { width: '100%', borderRadius: 12, borderWidth: 1, alignItems: 'center', paddingTop: 8 },
    podiumBlockNum:      { fontSize: 18, fontWeight: '800', color: '#D97706' },

    restList:       { gap: 6 },
    restRow:        { flexDirection: 'row', alignItems: 'center', gap: SP.sm, paddingVertical: 10, paddingHorizontal: SP.sm, borderRadius: 16, backgroundColor: C.bg, borderWidth: 1, borderColor: 'transparent' },
    restRowMe:      { borderColor: '#6EE7B7' },
    restRank:       { width: 20, textAlign: 'center', fontSize: 12, fontWeight: '600', color: C.muted },
    restInfo:       { flex: 1, minWidth: 0 },
    restNameRow:    { flexDirection: 'row', alignItems: 'center', gap: 5 },
    restName:       { fontSize: 13, fontWeight: '600', color: C.text, flexShrink: 1 },
    restLevel:      { fontSize: 11, color: C.muted, marginTop: 1 },
    restValueRow:   { flexDirection: 'row', alignItems: 'center', gap: 3 },
    restValue:      { fontSize: 13, fontWeight: '700', color: '#4B5563' },
    restUnit:       { fontSize: 11, color: C.muted },
    meBadge:        { backgroundColor: '#D1FAE5', borderRadius: 8, paddingHorizontal: 5, paddingVertical: 1 },
    meBadgeText:    { fontSize: 9, fontWeight: '700', color: '#065F46' },

    whyScroll:  { paddingRight: SP.md, paddingBottom: 4, gap: SP.sm },
    whyCard:    { width: width * 0.42, backgroundColor: C.surface, borderRadius: 20, padding: SP.md, alignItems: 'flex-start' },
    whyIconBox: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginBottom: SP.sm },
    whyKeyword: { fontSize: 14, fontWeight: '800', marginBottom: 3 },
    whySub:     { fontSize: 11, color: C.muted, lineHeight: 16 },

    testimonialContainer:  { marginBottom: SP.lg },
    testimonialTitle:      { fontSize: 16, fontWeight: '800', color: C.text, marginBottom: SP.sm },
    testimonialScroll:     { paddingRight: SP.md, gap: SP.sm },
    testimonialCard:       { width: width * 0.72, backgroundColor: C.surface, borderRadius: 20, padding: SP.md },
    testimonialAvatar:     { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', marginBottom: SP.xs },
    testimonialAvatarText: { fontSize: 16, fontWeight: '800' },
    testimonialStars:      { fontSize: 16, color: '#FBBF24', marginBottom: SP.xs },
    testimonialQuote:      { fontSize: 13, color: '#374151', fontStyle: 'italic', lineHeight: 19, marginBottom: SP.xs },
    testimonialName:       { fontSize: 12, fontWeight: '700', color: C.muted },
    bellBtn: { position: 'relative', marginRight: SP.sm, padding: 4 },
    bellBadge: { position: 'absolute', top: -2, right: -4, backgroundColor: '#EF4444', minWidth: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: C.brandDark },
    bellBadgeText: { color: '#FFF', fontSize: 9, fontWeight: '800' },

    // -- Modal List Thông báo --
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
    notifModalContainer: { backgroundColor: C.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, height: 0.75, paddingBottom: SP.lg },
    notifHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: SP.md, borderBottomWidth: 1, borderBottomColor: C.mutedLight },
    notifTitle: { fontSize: 18, fontWeight: '800', color: C.text },
    notifHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: SP.md },
    markReadText: { fontSize: 13, fontWeight: '700', color: C.brand },
    closeBtn: { padding: 4 },
    emptyNotif: { alignItems: 'center', justifyContent: 'center', marginTop: SP.xl * 2, gap: SP.sm },
    emptyNotifText: { color: C.muted, fontSize: 14 },

    // -- Item Thông báo --
    notifItem: { flexDirection: 'row', padding: SP.md, borderBottomWidth: 1, borderBottomColor: C.mutedLight, alignItems: 'center', gap: SP.sm },
    notifItemUnread: { backgroundColor: '#F0FDF4' },
    notifIconWrap: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
    notifContent: { flex: 1 },
    notifItemTitle: { fontSize: 15, fontWeight: '600', color: C.text, marginBottom: 2 },
    notifItemDesc: { fontSize: 13, color: C.muted, lineHeight: 18 },
    notifTime: { fontSize: 11, color: C.muted, marginTop: 4 },
    unreadDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: C.brand, marginLeft: SP.xs },

    // -- Modal Chi Tiết Thông báo --
    modalOverlayDark: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', padding: SP.lg },
    detailModal: { backgroundColor: C.surface, borderRadius: 24, overflow: 'hidden' },
    detailHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: SP.md, backgroundColor: C.mutedLight, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
    detailTag: { backgroundColor: C.brandLight, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, borderWidth: 1, borderColor: '#D1FAE5' },
    detailTagText: { fontSize: 10, fontWeight: '800', color: C.brandDark, textTransform: 'uppercase' },
    detailBody: { padding: SP.md, maxHeight:  0.5 },
    detailTitle: { fontSize: 18, fontWeight: '800', color: C.text, marginBottom: SP.sm, lineHeight: 24 },
    detailContentBox: { backgroundColor: C.mutedLight, padding: SP.md, borderRadius: 16, marginBottom: SP.md },
    detailContentText: { fontSize: 14, color: '#4B5563', lineHeight: 22 },
    detailTimeBox: { textAlign: 'right', fontSize: 12, color: C.muted, fontWeight: '500', marginBottom: SP.xs },
    detailBtn: { margin: SP.md, backgroundColor: C.brand, paddingVertical: 14, borderRadius: 16, alignItems: 'center' },
    detailBtnText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
});
